FROM rothnic/pyenv:alpine-base-latest
MAINTAINER nlr06886@gmail.com

# setup build environment
RUN apk-install build-base \
    libffi-dev \
    openssl-dev \
		libbz2 \
		libc6-compat \
		ncurses-dev \
		readline-dev \
		xz-dev \
		zlib-dev \
		sqlite-dev \
		patch \
		bzip2-dev \
		expat-dev \
		zlib-dev \
		gdbm-dev \
		paxmark \
		linux-headers \
		tcl-dev
