FROM rothnic/pyenv:alpine-base-latest
MAINTAINER nlr06886@gmail.com

# setup build environment
RUN apk-install gcc \
		make \
    libffi-dev \
    openssl-dev \
		libbz2 \
		libc6-compat \
		ncurses-dev \
		readline-dev \
		xz-dev \
		zlib-dev \
		sqlite-dev
